Add line number to text area: using CodeMirror library to create a editor
matheusgr/modeligado pull request #34
Opened 2021-10-01 19:04 UTC by MariaEduardaDeAzevedo

Issue #11 implementation.  
I chose to use the CodeMirror library, because it is easy to understand and simple to manipulate. 
It replaces all the logic used in textarea for the new editor model, based on a CodeMirror object. 
I kept the day theme, more specifically the same one from the Eclipse IDE, but there are also ways to implement a dark theme, since the library provides several ready-made themes.

2021-10-02 23:45 UTC, matheusgr requested changes
Nice work, only minor revisions here.

I also found that there is a bug on the parser code... can you test and fixed it? (parser ignores empty lines on how it count current linenumber that is used to show parser errors).

parser.js, should be:
```
const arrayOfLines = data.split(/\r?\n/)
    if (!arrayOfLines || !data.match(/[^\r\n]+/g)) {
      throw new ParseError(0, 'No text found.')
    }
```

2021-10-02 23:45 UTC, matheusgr commented on package.json
>      "devDependencies": {
Codemirror doesn't not neet to be a dependency here (since it will not be used by CLI).

Also, this package.json is malformed.

2021-10-02 23:45 UTC, matheusgr commented on edit.html
> +    <script src= "https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/codemirror.js"></script>
Use min version do reduce resource usage:
```
    <script src= "https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/codemirror.min.js"></script>
```

2021-10-02 23:45 UTC, matheusgr commented on edit.html
> +    <script src= "https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/mode/javascript/javascript.js"></script>
Avoid js mode (it is nice to have some highlight, but it doesn't follow modeligado syntax).

2021-10-02 23:45 UTC, matheusgr commented on codemirror.js
> +});
File not used. Delete.

2021-10-02 23:45 UTC, matheusgr commented on package-lock.json
> +{
Revert (since there will be no changes on package.json).

2021-10-02 23:45 UTC, matheusgr commented on yarn.lock
>    integrity sha1-7ihweulOEdK4J7y+UnC86n8+ce4=
Revert. There will be no changes on package.json.

2021-10-03 01:14 UTC, MariaEduardaDeAzevedo commented
I did some modifications based on code review

2021-10-04 11:19 UTC, matheusgr approved these changes
LGTM!

2021-10-04 11:20 UTC, matheusgr commented
@MariaEduardaDeAzevedo Can you do a rebase please?

2021-10-06 16:20 UTC, merged